# Terra scoreboard settings.

custom-scoreboard:
  config-version: 7
  enabled: true
  update-ticks: 20
  respect-other-scoreboards: true
  hide-numbers: true
  title-animation: ''
  title: '&2&lᴛᴇʀʀᴀɴᴀᴛɪᴏɴѕ'
  shadow:
    enabled: false
    color: '&8'
    prefix: ''
  job-name-color: '&f'
  lines:
    - '&8&m----------------'
    - '&7%date% &8| &7%server_time%'
    - '&f%player%'
    - ''
    - '&c⚐ &f%country% &7Lv.%country_level%'
    - '&a⛏ %job_color%%job% &7Lv.%job_level%'
    - '&b✦ &f%job_xp%&7/&f%job_xp_required% XP'
    - '&6⛃ &f%money%'
    - ''
    - '&9⌚ &f%playtime%'
    - ''
    - '&7ᴘʟᴀʏ.ᴛᴇʀʀᴀɴᴀᴛɪᴏɴѕ.ɴᴇᴛ'
    - '&8&m----------------'

scoreboard_logo:
  change-interval: 25
  texts:
    - '&2&lᴛᴇʀʀᴀɴᴀᴛɪᴏɴѕ'
