info:
  namespace: terrahud

font_images:
  # Top status panels
  # Lower y_position values move the panel image down from the top bossbar line.
  top_status_panel:
    suggest_in_command: false
    path: font/hud/top_status/panel.png
    scale_ratio: 14
    y_position: 5
  top_status_location_panel:
    suggest_in_command: false
    path: font/hud/top_status/location_panel.png
    scale_ratio: 14
    y_position: 7
  top_status_job_panel:
    suggest_in_command: false
    path: font/hud/top_status/job_panel.png
    scale_ratio: 14
    y_position: 7
  top_status_money_panel:
    suggest_in_command: false
    path: font/hud/top_status/money_panel.png
    scale_ratio: 14
    y_position: 7
